---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - { role: ks-devops/sonarqube, when: "sonarqube_enable == true" }
    - { role: openpitrix, when: "openpitrix_enable == true" }
    - ks-core
    - { role: metrics-server, when: "metrics_server_enable == true" }
    - { role: ks-monitor, when: "monitoring_enable == true" }
    - { role: ks-logging, when: "logging_enable == true" }
    - { role: ks-notification, when: "notification_enable == true" }
    - { role: ks-alerting, when: "alerting_enable == true" }
    - ks-devops
    - ks-core/ks-apiserver
    - { role: ks-istio, when: "istio_enable == true" }
