---

- name: ks-controller-manager | Getting ks-controller-manager installation files
  copy:
    src: "ks-controller-manager"
    dest: "{{ kubesphere_dir }}/"
  tags:
    - upgrade

- name: ks-controller-manager | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/ks-controller-manager/{{ item.file }}"
  with_items:
    - { name: ks-controller-manager, file: ks-controller-manager.yaml, type: deploy }
  tags:
    - upgrade


- name: ks-controller-manager | Creating Controller Manager
  shell: "{{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-controller-manager/ks-controller-manager.yaml"
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr"


- name: KubeSphere | Restarting ks-controller-manager
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-controller-manager --replicas=0 &&
    {{ bin_dir }}/kubectl -n kubesphere-system scale deployment ks-controller-manager --replicas=1