---
- name: Kubesphere | Checking account init
  shell: >
    {{ bin_dir }}/kubectl get users admin
  register: kubesphere_user_check
  failed_when: "kubesphere_user_check.stderr and 'NotFound' not in kubesphere_user_check.stderr"

- name: Kubesphere | Init account
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/ks-init/admin.yaml
  when:
    - kubesphere_user_check.stderr is defined
    - kubesphere_user_check.stderr.find("NotFound") != -1

- name: Kubesphere | Label namespace for network policy
  shell: >
    for ns in `kubectl get ns -o jsonpath="{.items[*].metadata.name}"`; do kubectl label  ns $ns kubesphere.io/namespace=$ns --overwrite; done
  ignore_errors: True

