- hosts: all
  gather_facts: False
  tasks:
    - name: Fetch /etc/os-release
      raw: cat /etc/os-release
      register: os_release
      changed_when: false
      environment: {}
    - name: Check os release
      set_fact:
        os_release: >-
          {%- if 'Ubuntu' in os_release.stdout -%}
           ubuntu
          {%- endif -%}
          {%- if 'CentOS' in os_release.stdout -%}
           centos
          {%- endif -%}

    - name: Add APT repositories(centos)
      raw: systemctl stop firewalld
      when: os_release == "centos"
      ignore_errors: True

    - name: Add APT repositories(ubuntu)
      raw:  ufw disable
      when: os_release == "ubuntu"
      ignore_errors: True