---
- name: Kubesphere | Checking openpitrix common component
  shell: >
    {{ bin_dir }}/kubectl get pod -n openpitrix-system | grep openpitrix-hyperpitrix
  register: openpitrix_health_check
  ignore_errors: True

- import_tasks: openpitrix-install.yaml
  when:
    - openpitrix_health_check.stdout.find("Running") == -1



