---
- name: OpenPitrix | Getting OpenPitrix installation files
  copy:
    src: "openpitrix"
    dest: "{{ kubesphere_dir }}/"

- name: OpenPitrix | Getting OpenPitrix installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: openpitrix/hyperpitrix-kubernetes/scripts, file: deploy-k8s.sh }
    - { path: openpitrix, file: version.sh }

- name: OpenPitrix | Installing OpenPitrix(1)
  shell: >
    chmod +x -R {{ kubesphere_dir }}/openpitrix

- name: OpenPitrix | Installing OpenPitrix(2)
  shell: >
    {{ kubesphere_dir }}/openpitrix/hyperpitrix-kubernetes/scripts/deploy-k8s.sh -n openpitrix-system -v {{ openpitrix_version }} -a