---

- name: ks-devops | Getting sonarqube installation files
  copy:
    src: "sonarqube"
    dest: "{{ kubesphere_dir }}/"


- name: ks-devops | Waitting apiservices/v1beta1.metrics.k8s.io
  shell: >
    {{ bin_dir }}/kubectl --namespace=kube-system wait --for=condition=Available --timeout=5m apiservices/v1beta1.metrics.k8s.io
  when:
    - metrics-server.enabled is defined
    - metrics-server.enabled == true

- name: ks-devops | Creating ks-jenkins webhook(external)
  uri:
    url: "{{ sonar_server_url }}/api/webhooks/create"
    method: POST
    user: "{{ sonar_server_token }}"
    password: ""
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      name: ks-jenkins
      url: 'http://ks-jenkins.kubesphere-devops-system.svc.cluster.local/sonarqube-webhook/'
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is  defined
    - devops.sonarqube.externalSonarToken is  defined


- name: Sonarqube | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/sonarqube/{{ item.file }}"
  with_items:
    - { name: custom-values-sonarqube, file: custom-values-sonarqube.yaml }
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is not defined
    - devops.sonarqube.externalSonarToken is not defined


- name: Sonarqube | Deploy Sonarqube
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-sonarqube 
    {{ kubesphere_dir }}/sonarqube/sonarqube
    -f {{ kubesphere_dir }}/sonarqube/custom-values-sonarqube.yaml 
    --namespace kubesphere-devops-system
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is not defined
    - devops.sonarqube.externalSonarToken is not defined
