---

- name: ks-devops | Getting sonarqube installation files
  copy:
    src: "sonarqube"
    dest: "{{ kubesphere_dir }}/"


#- name: jenkins-update-center | Creating manifests
#  template:
#    src: "{{ item.file }}.j2"
#    dest: "{{ kubesphere_dir }}/sonarqube/jenkins-update-center/values.yaml"
#  with_items:
##    - { name: values-jenkins-uc, file: values-jenkins-uc.yaml, type: values }


#- name: jenkins-update-center | Start Jenkins plugins update center
#  shell: "{{ bin_dir }}/helm upgrade --install uc {{ kubesphere_dir }}/sonarqube/jenkins-update-center --namespace kubesphere-devops-system"
#  register: result
#  until: result.rc == 0
#  retries: 20
#  delay: 30


- name: ks-devops | Creating ks-jenkins webhook(external)
  uri:
    url: "{{ sonar_server_url }}/api/webhooks/create"
    method: POST
    user: "{{ sonar_server_token }}"
    password: ""
    force_basic_auth: yes
    body_format: form-urlencoded
    body:
      name: ks-jenkins
      url: 'http://ks-jenkins.kubesphere-devops-system.svc.cluster.local/sonarqube-webhook/'
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is  defined
    - devops.sonarqube.externalSonarToken is  defined


- name: Sonarqube | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/sonarqube/{{ item.file }}"
  with_items:
    - { name: custom-values-sonarqube, file: custom-values-sonarqube.yaml }
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is not defined
    - devops.sonarqube.externalSonarToken is not defined


- name: Sonarqube | Deploy Sonarqube
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-sonarqube 
    {{ kubesphere_dir }}/sonarqube/sonarqube
    -f {{ kubesphere_dir }}/sonarqube/custom-values-sonarqube.yaml 
    --namespace kubesphere-devops-system
  when:
    - devops.sonarqube.enabled is defined
    - devops.sonarqube.enabled == true
    - devops.sonarqube.externalSonarUrl is not defined
    - devops.sonarqube.externalSonarToken is not defined
