---

- name: logsidecar-injector | Getting logsidecar-injector installation files
  copy:
    src: "logsidecar-injector"
    dest: "{{ kubesphere_dir }}/"

- name: logsidecar-injector | Creating manifests
  template:
    src: "custom-values-logsidecar-injector.yaml.j2"
    dest: "{{ kubesphere_dir }}/logsidecar-injector/custom-values-logsidecar-injector.yaml"

- name: logsidecar-injector | check logsidecar-injector
  shell: >
    {{ bin_dir }}/helm list -f logsidecar-injector -n kubesphere-logging-system
  register: logsidecar_injector_check
  ignore_errors: True

- name: logsidecar-injector | Deploy logsidecar-injector
  shell: >
    {{ bin_dir }}/helm upgrade --install logsidecar-injector
    {{ kubesphere_dir }}/logsidecar-injector
    -f {{ kubesphere_dir }}/logsidecar-injector/custom-values-logsidecar-injector.yaml
    -n kubesphere-logging-system
    --force
  register: deploy_result
  until: deploy_result is succeeded
  retries: 3
  delay: 10
  when:
    - (logsidecar_injector_check.stdout.find("DEPLOYED") == -1) or (logsidecar_injector_check.stdout.find("v0.1.0") == -1)
