---
# Delete prometheus-system and related pvcs after 7 days
- name: ks-monitor | calc prometheus system cleanup schedule 
  shell: |
    retention=$((`date +%s` + 3600*24*7))
    min=`date --date=@$retention +%M | sed -e 's/^0//'`
    hour=`date --date=@$retention +%H | sed -e 's/^0//'`
    day=`date --date=@$retention +%d | sed -e 's/^0//'`
    month=`date --date=@$retention +%m | sed -e 's/^0//'`
    echo "$min $hour $day $month *"
    exit 0
  register: prometheus_system_cleanup_schedule

- name: ks-monitor | calc prometheus system pvc cleanup schedule 
  shell: |
    retention=$((`date +%s` + 3600*24*7 + 3600))
    min=`date --date=@$retention +%M | sed -e 's/^0//'`
    hour=`date --date=@$retention +%H | sed -e 's/^0//'`
    day=`date --date=@$retention +%d | sed -e 's/^0//'`
    month=`date --date=@$retention +%m | sed -e 's/^0//'`
    echo "$min $hour $day $month *"
    exit 0
  register: prometheus_system_pvc_cleanup_schedule

- name: ks-monitor | Setup cronjobs to cleanup prometheus-system and related pvcs 
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/prometheus/upgrade