---

- name: ks-events | getting ks-events installation files
  copy:
    src: "kube-events"
    dest: "{{ kubesphere_dir }}/ks-events/"

- name: ks-events | getting ks-events installation files
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.path }}/{{ item.file }}"
  with_items:
    - { path: ks-events, file: custom-values-events.yaml }


- name: ks-events | check ks-events
  shell: >
    {{ bin_dir }}/helm list -f ks-events -n kubesphere-logging-system
  register: events_check
  ignore_errors: True


- name: ks-events | deploy ks-events
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-events
    {{ kubesphere_dir }}/ks-events/kube-events
    -f {{ kubesphere_dir }}/ks-events/custom-values-events.yaml
    -n kubesphere-logging-system
    --force
  register: deploy_result
  until: deploy_result is succeeded
  retries: 3
  delay: 10
  when:
    - (events_check.stdout.find("DEPLOYED") == -1) or (events_check.stdout.find("v0.1.0") == -1)

