apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: logsidecar-injector
  namespace: kubesphere-logging-system
webhooks:
  - name: logsidecar-injector.logging.kubesphere.io
    failurePolicy: Fail
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
        resources:
          - pods
    clientConfig:
      service:
        namespace: kubesphere-logging-system
        name: logsidecar-injector
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZekNDQWt1Z0F3SUJBZ0lKQUxiSmhKTWxWU2Q3TUEwR0NTcUdTSWIzRFFFQkN3VUFNRWd4Q3pBSkJnTlYKQkFZVEFrTk9NUXN3Q1FZRFZRUUlEQUpJUWpFTE1Ba0dBMVVFQ2d3Q1VVTXhIekFkQmdOVkJBTU1GbXh2WjNOcApaR1ZqWVhJdGFXNXFaV04wYjNJdFkyRXdIaGNOTVRrd09USXpNREkwT0RFeVdoY05ORGN3TWpBNE1ESTBPREV5CldqQklNUXN3Q1FZRFZRUUdFd0pEVGpFTE1Ba0dBMVVFQ0F3Q1NFSXhDekFKQmdOVkJBb01BbEZETVI4d0hRWUQKVlFRRERCWnNiMmR6YVdSbFkyRnlMV2x1YW1WamRHOXlMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBNUI4bHRDYmNsOS9FRUlJNlhpMHdrdWVhWkY1bC96cDQ5SzlUTS9qelpXakNWRVB5CkNMRGNHeHVJd3BGaHV0YUNMSEhCMDBmRllyNnhOSklnZUsxdVEwakZPc2gyL1lTZ1RTRnA5czJhc2tkTk9ELzgKb1RkU1RSdFdzUndGZGRBYittd2JGUWdONmYxYWQxaEwzMnVrQ0h3WGtQZ3E1cXNpSHNMamgzVnlLeGMrOHI2bAppeTh6MlVySmJoNEErYWlVWnpLTFpBQkJPSU45UHZ2UTZIYUFBZDNncnpMcEIvYTVJdFB4U2pLUzRYQ3FUeDVZCmxxeWU2aXBiaDlRcmlhU1lKM3NiLzNiTWhmY3JySnFYbTRXWHoxbzhza2Z6REFwWWQ2Y2ozL3VqbkpwaklLSWkKdzBDemR6UEQ4djFHcW9TZnpMMWV4UWROaHBub05jK28vaXNaWXdJREFRQUJvMUF3VGpBZEJnTlZIUTRFRmdRVQpRVXZ4T1JQWDFsM0ZVKzBxaHlKQTNvdHpadHd3SHdZRFZSMGpCQmd3Rm9BVVFVdnhPUlBYMWwzRlUrMHFoeUpBCjNvdHpadHd3REFZRFZSMFRCQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFUaXZER3ZSSTlySSsKd2tiUjVBMWQ1UWtwb3g3NndaVVR0UVJGaXRFY1o5dWlzQUNGM3cxYjVnY2oyYVArSzQrSTNFUm8yME8xOHhvMQpISkF1STlYVXhvcjFOVytvU09rVmh2NTZMdUtESHhQcW1PR3BFWFJGRjBGTDFQSlhNM0VpRE9GdllHc1Z4UElPCmNHU0VUUm9ZQ2J3TmMvcUVkNjI2cEFtOWNDUmpLWSt6SlBNVDEveTU1TWVwTmhTQnN6M0l0T3dJV2lMMTZ6aEkKMnkwRWNoQ0NqUFBTbVRJWTdaYzNBOVJQczdkcTBxcFRkd0hoZWozZnM1VkZFb0pUSmRJd2YvaXF3THk2a3RtLwpPejhRa0JZa1VPMENjL3FmVEtLQUUvQVdkemQyWmlLRDZRMnZPLzM5Q0V3RzhMU3Q2anZjdGlRZHVBb2pZSEFrCnduYjBXV2RLVXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    namespaceSelector:
      matchExpressions:
      - key: logging.kubesphere.io/logsidecar-injection
        operator: In
        values:
        - enabled