---
- name: check k8s version
  shell: >
    {{ bin_dir }}/kubectl version -o json | jq '.serverVersion.gitVersion' | sed s/\"//g
  register: kubernetes_version

- name: init k8s version
  set_fact: >
    k8s_version: {{ kubernetes_version.stdout }}

- name: Stop if kuernetes version is nonsupport
  assert:
    that: kubernetes_version.stdout is version('v1.16.0', '<=')
    msg: The current k8s version is not supported

- name: check k8s version
  shell: >
    {{ bin_dir }}/kubectl version -o json | jq '.serverVersion.gitVersion' | sed s/\"//g
  register: kubernetes_version
