#- name: Kubesphere | Getting mysql installation files
#  copy:
#    src: "{{ item }}"
#    dest: "{{ kubesphere_dir }}/"
#  loop:
#    - "mysql-ha"
#
#
#- name: Kubesphere | Creating manifests
#  template:
#    src: "{{ item.file }}.j2"
#    dest: "{{ kubesphere_dir }}/{{ item.file }}"
#  with_items:
#    - { name: custom-values-mysql, file: custom-values-mysql.yaml }
#
#
#- name: Kubesphere | Deploy mysql
#  shell: >
#    {{ bin_dir }}/helm upgrade --install ks-mysql
#    {{ kubesphere_dir }}/mysql-ha
#    -f {{ kubesphere_dir }}/custom-values-mysql.yaml
#    --set fullnameOverride=mysql
#    --namespace kubesphere-system


- name: Kubesphere | Deploying common component
  shell: >
    {{ bin_dir }}/kubectl -n kubesphere-system apply -f {{ kubesphere_dir }}/common/{{ item }}
  loop:
    - "mysql.yaml"
  register: import
  failed_when:
    - "import.stderr and 'is immutable after creation except resources.requests for bound claims' not in import.stderr"
    - "import.stderr and 'is forbidden' not in import.stderr"
#  when: devops.enabled or openpitrix.enabled or notification.enabled or alerting.enabled