- name: Kubesphere | Getting redis installation files
  copy:
    src: "{{ item }}"
    dest: "{{ kubesphere_dir }}/"
  loop:
    - "redis-ha"


- name: Kubesphere | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/{{ item.file }}"
  with_items:
    - { name: custom-values-redis, file: custom-values-redis.yaml }


- name: Kubesphere | Deploy redis
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-redis
    {{ kubesphere_dir }}/redis-ha
    -f {{ kubesphere_dir }}/custom-values-redis.yaml
    --set fullnameOverride=redis
    --namespace kubesphere-system