---

- name: ks-devops | Getting gitlab installation files
  copy:
    src: "gitlab"
    dest: "{{ kubesphere_dir }}/"


- name: Gitlab | Creating manifests
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kubesphere_dir }}/gitlab/{{ item.file }}"
  with_items:
    - { name: custom-values-gitlab, file: custom-values-gitlab.yaml, type: values }


- name: Gitlab | Deploy Gitlab OpenldapSecret
  shell: >
    {{ bin_dir }}/kubectl apply -f {{ kubesphere_dir }}/gitlab/openldap-secret.yml -n kubesphere-devops-system
  register: import
  failed_when: "import.stderr and 'AlreadyExists' not in import.stderr"


- name: Gitlab | Deploy Gitlab
  shell: >
    {{ bin_dir }}/helm upgrade --install ks-gitlab {{ kubesphere_dir }}/gitlab/gitlab-1.6.1.tgz
    -f {{ kubesphere_dir }}/gitlab/custom-values-gitlab.yaml
    --namespace kubesphere-devops-system
  register: import
  until: import is succeeded
  retries: 3
  delay: 5

