apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-console
    tier: frontend
    version: v2.1.1
  name: ks-console
  namespace: kubesphere-system
spec:
  ports:
    - name: nginx
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: ks-console
    tier: frontend
    version: v2.1.1
  type: NodePort