---

- hosts: localhost
  gather_facts: false
  roles:
    - kubesphere-defaults
    - role: ks-events
      when:
        - "status.events is not defined or status.events.status is not defined or status.events.status != 'enabled'"