apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  labels:
    logging.kubesphere.io/enabled: 'true'
    logging.kubesphere.io/component: "auditing"
  name: es-auditing
  namespace: kubesphere-logging-system
spec:
  es:
    host: elasticsearch-logging-data.kubesphere-logging-system.svc
    logstashFormat: true
    logstashPrefix: ks-logstash-auditing
    port: 9200
  match: kube_auditing

