---

logging:
  elasticsearchMasterReplicas: 1
  elasticsearchDataReplicas: 2
  logsidecarReplicas: 2
  elasticsearchVolumeSize: 20Gi
  logMaxAge: 7
  elkPrefix: logstash
  containersLogMountedPath: ""
  kibana:
    enable: false
# externalElasticsearchUrl:
# externalElasticsearchPort:

