---

logging:
  elasticsearchMasterReplica: 1
  elasticsearchDataReplica: 2
  elasticsearchVolumeSize: 20Gi
  logMaxAge: 7
  elkPrefix: logstash
  containersLogMountedPath: ""
  kibana:
    enable: false
# externalElasticsearchUrl:
# externalElasticsearchPort:

